TwitterDataCollection/tdc/search/urls.py
from django.conf.urls import  url
from . import views

urlpatterns = [
    url(r'^$', views.index),
    url(r'^search', views.go_search, name="go_search")
]

TwitterDataCollection/tdc/tdc/urls.py
from django.conf.urls import include,url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'', include('search.urls')),
]

TwitterDataCollection/tdc/search/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

TwitterDataCollection/tdc/search/forms.py
from django import forms


class hastag(forms.Form):
    has = forms.CharField(required=True, label='',widget=forms.TextInput(attrs={'autocomplete':'off'}))
    time = forms.CharField()

TwitterDataCollection/tdc/search/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.shortcuts import render, redirect
from .forms import hastag
import neo4j as n
import thread


def index(request):
    form = hastag()
    hastag_valid = hastag(request.POST or None)
    if hastag_valid.is_valid():
        data = hastag_valid.cleaned_data
        has = data.get("has")
        time = data.get("time")
        print has,": ", time," minutes"
        x = n.neo4j()
        thread.start_new(x.main, (has, time))
        return redirect('go_search')
    return render(request, "index.html", {"form": form})


def go_search(request):
    return render(request, "search.html")

TwitterDataCollection/tdc/templates/index.html
{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Twitter</title>

    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
    <link href="https://fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext" rel="stylesheet" type="text/css">
    <link rel="stylesheet" type="text/css" href="{% static 'css/index.css' %}">


</head>

<body>
    <div class = "windows">
        <div class = "top">
            <div class = "title">
                <h1>Twitter Data Collection</h1>
            </div>
        </div>
        <div class = "bottom">
            <div class = "btn">


            <form method="POST">
                {% csrf_token %}
                {{form.has}}
                {{form.time}}
                <div class="inputDivRange">
                    <div id="valueRange"></div>
                    <input id="inputR" type="range" value="1" min="0" max="100" autocomplete="off">
                </div>
                <input type="submit" value="Start" />
            </form>
            </div>
        </div>
    </div>


</body>

<script>


    var elInput = document.querySelector('#inputR');
    var time = document.querySelector('#id_time');
    if (elInput) {
            var valueRange = document.querySelector('#valueRange');
            if (valueRange) {
                valueRange.innerHTML = elInput.value;
                time.value = elInput.value;
                elInput.addEventListener('input', function() {
                valueRange.innerHTML = elInput.value;
                time.value = elInput.value;
            }, false);
        }
    }
</script>
</html>

TwitterDataCollection/tdc/templates/search.html
{% load staticfiles %}
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>Twitter</title>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
        <link href="https://fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext" rel="stylesheet" type="text/css">
        <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400" rel="stylesheet">
        <link rel="stylesheet" href="{% static 'css/search.css' %}">

    </head>

    <body>
        <div id = "info">
            <div id= "header">
                <span id = "inf"><b>Information</b></span>
                <div id = "closeInfo" onclick="closeInfo()">
                    <i class="fa fa-close" style="font-size:170%"></i>
                </div>
            </div>
            <div  id="containsInfo">
                <div id = "profilePhoto">
                    <img id = "imgP" src="">
                </div>
                <div id = "name">
                    <p id = nameP> Name:</p>
                </div>
                <div id = "infoUsername">
                    <p id = "usernameP">Username:</p>
                </div>
                <div id = "description">
                    <p id="descriptionP">Description:</p>
                </div>
                <div id = "verified">
                    <p id = "verifiedP">verified:</p>
                </div>
                <div id = "profile_id">
                    <p id = "profile_idP">id:</p>
                </div>
                <div id = "followers">
                    <p id = "followersP"> followers:</p>
                </div>
                <hr>
                <div id = "tweet">
                    <p id="tweetP">Tweet:</p>
                </div>
                <div id = "location">
                    <p id = "locationP">Location:</p>
                </div>
                <div id = "time">
                    <p id = "timeP">time:</p>
                </div>

                <div id = "url">
                    <p id = "urlP">Url:</p>
                </div>
            </div>
        </div>
        <canvas id="network" width="1400" height="700"></canvas>
    </body>

        <script src="{% static 'lib/neo4j-web.min.js' %}"></script>
        <script src="https://d3js.org/d3.v4.min.js"></script>
        <script src="../static/js/search.js"></script>

</html>